variables:
  S3_BUCKET_STAGING_NAME: "staging-air-tag"
  CLOUDFRONT_ID: "EGR9SY7RO24RK"

stages:
  - prep
  - build
  - deploy

image: node:latest

prep:
  stage: prep
  script:
    - yarn install
  cache:
    paths:
      - node_modules
  only:
    - staging

build staging:
  stage: build
  script:
    - echo "BASE_IMAGE_URL=$BASE_IMAGE_URL" >> .env
    - echo "BE_API_URL=$BE_API_URL" >> .env
    - echo "HOME_URL=$HOME_URL" >> .env
    - echo "KEYCLOAK_API_URL=$KEYCLOAK_API_URL" >> .env
    - echo "MOCK_API_PORT=$MOCK_API_PORT" >> .env
    - echo "SERVER_PORT=$SERVER_PORT" >> .env
    - yarn build
    - yarn generate
  cache:
    paths:
      - node_modules
      - dist
  only:
    - staging

deploy to staging:
  stage: deploy
  environment: staging
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  cache:
    paths:
      - node_modules
      - dist
  script:
    - cd dist
    - aws s3 rm s3://$S3_BUCKET_STAGING_NAME --recursive
    - aws s3 cp ./ s3://$S3_BUCKET_STAGING_NAME/ --recursive --include "*"
    - aws cloudfront create-invalidation --distribution-id EGR9SY7RO24RK --paths "/*"
  only:
    variables:
      - $CI_COMMIT_BRANCH == 'staging'
