variables:
  S3_BUCKET_STAGING_NAME: "staging-air-tag"
  CLOUDFRONT_ID: "EGR9SY7RO24RK"

stages:
  - prep
  - build
  - deploy

image: node:latest

prep:
  stage: prep
  script:
    - npm install
  cache:
    paths:
      - node_modules
  only:
    - staging

build staging:
  stage: build
  script:
    - yarn build
  cache:
    paths:
      - node_modules
      - build
  only:
    - staging

deploy to staging:
  stage: deploy
  environment: staging
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  cache:
    paths:
      - node_modules
      - build
  script:
    - cd build
    - aws s3 rm s3://$S3_BUCKET_STAGING_NAME --recursive
    - aws s3 cp ./ s3://$S3_BUCKET_STAGING_NAME/ --recursive --include "*"
    - aws cloudfront create-invalidation --distribution-id EGR9SY7RO24RK --paths "/*"
  only:
    variables:
      - $CI_COMMIT_BRANCH == 'staging'
