variables:
  S3_BUCKET_STAGING_NAME: "staging-air-tag"
  CLOUDFRONT_ID: "EGR9SY7RO24RK"

stages:
  - prep
  - build
  - deploy

image: node:latest

prep:
  stage: prep
  script:
    - yarn install
    - echo "$BASE_IMAGE_URL" >> test.env
    - echo "$BE_API_URL" >> test.env
    - echo "$HOME_URL" >> test.env
    - echo "$KEYCLOAK_API_URL" >> test.env
    - echo "$MOCK_API_PORT" >> test.env
    - echo "$SERVER_PORT" >> test.env
    - cat test.env
  cache:
    paths:
      - node_modules
  only:
    - staging

build staging:
  stage: build
  script:
    - yarn build
    - yarn generate
  cache:
    paths:
      - node_modules
      - dist
  only:
    - staging

deploy to staging:
  stage: deploy
  environment: staging
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  cache:
    paths:
      - node_modules
      - dist
  script:
    - cd dist
    - aws s3 rm s3://$S3_BUCKET_STAGING_NAME --recursive
    - aws s3 cp ./ s3://$S3_BUCKET_STAGING_NAME/ --recursive --include "*"
    - aws cloudfront create-invalidation --distribution-id EGR9SY7RO24RK --paths "/*"
  only:
    variables:
      - $CI_COMMIT_BRANCH == 'staging'
