export enum RECEIPT_ACTION {
    REQUEST_ACTION_UNKNOWN = 'REQUEST_ACTION_UNKNOWN',
    REQUEST_ACTION_TO_IMPORT_BOX = 'REQUEST_ACTION_TO_IMPORT_BOX',
    REQUEST_ACTION_TO_EXPORT_BOX = 'REQUEST_ACTION_TO_EXPORT_BOX',
    REQUEST_ACTION_TO_INVENTORY = 'REQUEST_ACTION_TO_INVENTORY',
}

export enum RECEIPT_STATUS {
    REQUEST_STATUS_DRAFT = 'REQUEST_STATUS_DRAFT',
    REQUEST_STATUS_SAVED = 'REQUEST_STATUS_SAVED'
}

