export enum REPORT_STATUS {
  NEW = 'REPORT_NEW',
  IN_PROGRESS = 'REPORT_IN_PROGRESS',
  READY = 'REPORT_READY',
  CANCELED = 'REPORT_CANCELLED',
  DELIVERING = 'REPORT_DELIVERING',
  SETTED = 'REPORT_SETTED',
  ACCEPTED = 'REPORT_ACCEPTED',
  DELIVERED = 'REPORT_DELIVERED',
  RETURNE = 'REPORT_RETURNE'
}
