export enum RECEIPT_STATUS {
    REQUEST_STATUS_DRAFT = 'REQUEST_STATUS_DRAFT',
    REQUEST_STATUS_SAVED = 'REQUEST_STATUS_SAVED'
}
// "- Action:
// + REQUEST_ACTION_UNKNOWN (0)
// + REQUEST_ACTION_TO_IMPORT_BOX (1)
// + REQUEST_ACTION_TO_EXPORT_BOX (2)
// + REQUEST_ACTION_TO_INVENTORY (3)

// - Status:
// + REQUEST_STATUS_DRAFT (0)
// + REQUEST_STATUS_SAVED (1)

// - userStatus:
// + USER_STATUS_UNKNOWN (0)
// + USER_STATUS_INACTIVE (1)
// + USER_STATUS_ACTIVE (2)"