export enum STOCK_OUT_ACTION {
  ORDER_DETAIL = 'ORDER_DETAIL',
  ORDER_PICK_ITEM = 'ORDER_PICK_ITEM',
}

export enum ORDER_STATUS {
  NEW = 'DELIVERY_ORDER_STATUS_NEW',
  IN_PROGRESS = 'DELIVERY_ORDER_STATUS_IN_PROGRESS',
  READY = 'DELIVERY_ORDER_STATUS_READY',
  CANCELED = 'DELIVERY_ORDER_STATUS_CANCELLED',
  DELIVERING = 'DELIVERY_ORDER_STATUS_DELIVERING',
  DELIVERED = 'DELIVERY_ORDER_STATUS_DELIVERED',
  RETURNE = 'DELIVERY_ORDER_STATUS_RETURNE'
}
